-- Existing grants have null scope columns and are consequently unusable by the live media handler.
ALTER TABLE document_access_grants ADD COLUMN organization_id TEXT REFERENCES organizations(id);
ALTER TABLE document_access_grants ADD COLUMN provider TEXT;
ALTER TABLE document_access_grants ADD COLUMN attempt_id TEXT REFERENCES attempts(id);
ALTER TABLE document_access_grants ADD COLUMN document_sha256 TEXT;
CREATE INDEX document_access_grants_expiry ON document_access_grants(expires_at);
ALTER TABLE attempts ADD COLUMN bridge_claimed_at TEXT;
CREATE TABLE provider_drafts(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),document_id TEXT NOT NULL,document_sha256 TEXT NOT NULL,sender_id TEXT NOT NULL,sender_address TEXT NOT NULL,provider TEXT NOT NULL CHECK(provider='pingen'),provider_id TEXT,recipient_json TEXT NOT NULL CHECK(json_valid(recipient_json)),expected_address TEXT NOT NULL,options_json TEXT NOT NULL CHECK(json_valid(options_json)),ceiling_minor INTEGER NOT NULL CHECK(ceiling_minor>=0),currency TEXT NOT NULL CHECK(currency='EUR'),status TEXT NOT NULL CHECK(status IN ('preparing','prepared','unknown')),provider_status TEXT,request_hash TEXT NOT NULL,idempotency_key TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,claimed_dispatch_id TEXT UNIQUE REFERENCES dispatches(id),UNIQUE(organization_id,id),UNIQUE(organization_id,idempotency_key),UNIQUE(provider,provider_id),FOREIGN KEY(organization_id,document_id) REFERENCES documents(organization_id,id),FOREIGN KEY(organization_id,sender_id) REFERENCES senders(organization_id,id));
CREATE INDEX provider_drafts_org_page ON provider_drafts(organization_id,created_at DESC,id DESC);
CREATE TRIGGER immutable_provider_draft BEFORE UPDATE ON provider_drafts WHEN NEW.organization_id<>OLD.organization_id OR NEW.document_id<>OLD.document_id OR NEW.document_sha256<>OLD.document_sha256 OR NEW.sender_id<>OLD.sender_id OR NEW.sender_address<>OLD.sender_address OR NEW.provider<>OLD.provider OR (OLD.provider_id IS NOT NULL AND NEW.provider_id IS NOT OLD.provider_id) OR NEW.recipient_json<>OLD.recipient_json OR NEW.expected_address<>OLD.expected_address OR NEW.options_json<>OLD.options_json OR NEW.ceiling_minor<>OLD.ceiling_minor OR NEW.currency<>OLD.currency OR NEW.request_hash<>OLD.request_hash OR NEW.idempotency_key<>OLD.idempotency_key OR (OLD.claimed_dispatch_id IS NOT NULL AND NEW.claimed_dispatch_id IS NOT OLD.claimed_dispatch_id) BEGIN SELECT RAISE(ABORT,'immutable_provider_draft'); END;
