-- Internal sender status 'verified' records the authenticated administrator's
-- authorization to use the identity, never verification of a physical address.
CREATE TABLE postal_sender_declarations(organization_id TEXT PRIMARY KEY REFERENCES organizations(id), sender_id TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES users(id), sender_name TEXT NOT NULL, sender_address TEXT NOT NULL, authorization_basis TEXT NOT NULL CHECK(authorization_basis='authenticated_administrator_declaration'), physical_address_verified INTEGER NOT NULL CHECK(physical_address_verified=0), profile_json TEXT NOT NULL CHECK(json_valid(profile_json)), audit_id TEXT NOT NULL REFERENCES audit_log(id), created_at TEXT NOT NULL, UNIQUE(organization_id,sender_id), FOREIGN KEY(organization_id,sender_id) REFERENCES senders(organization_id,id));
CREATE TRIGGER immutable_postal_sender_declaration BEFORE UPDATE ON postal_sender_declarations BEGIN SELECT RAISE(ABORT,'immutable_postal_sender_declaration'); END;
CREATE TRIGGER retained_postal_sender_declaration BEFORE DELETE ON postal_sender_declarations BEGIN SELECT RAISE(ABORT,'immutable_postal_sender_declaration'); END;
-- Each administrator-authorized price qualification retains its exact eight
-- immutable policy IDs. Expiry renewal cannot supersede a revoked current policy.
CREATE TABLE postal_setup_policy_generations(organization_id TEXT NOT NULL, generation INTEGER NOT NULL CHECK(generation>0), sender_id TEXT NOT NULL, policy_ids_json TEXT NOT NULL CHECK(json_valid(policy_ids_json) AND json_array_length(policy_ids_json)=8), profile_json TEXT NOT NULL CHECK(json_valid(profile_json)), audit_id TEXT NOT NULL REFERENCES audit_log(id), created_at TEXT NOT NULL, expires_at TEXT NOT NULL CHECK(expires_at>created_at), PRIMARY KEY(organization_id,generation), FOREIGN KEY(organization_id,sender_id) REFERENCES postal_sender_declarations(organization_id,sender_id));
CREATE TRIGGER immutable_postal_setup_policy_generation BEFORE UPDATE ON postal_setup_policy_generations BEGIN SELECT RAISE(ABORT,'immutable_postal_setup_policy_generation'); END;
CREATE TRIGGER retained_postal_setup_policy_generation BEFORE DELETE ON postal_setup_policy_generations BEGIN SELECT RAISE(ABORT,'immutable_postal_setup_policy_generation'); END;
