/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.preview.jsonc --include-runtime=false --env-interface=PreviewEnv apps/preview/worker-configuration.d.ts` (hash: b4459298cf78a819cb81b7d3bca4c924)
interface __BaseEnv_PreviewEnv {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_PreviewEnv {}
}
interface PreviewEnv extends __BaseEnv_PreviewEnv {}
