Foreground yes
LocalSocket /tmp/clamav/clamd.sock
LocalSocketMode 600
FixStaleSocket yes
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp/clamav
LeaveTemporaryFiles no
User clamav
LogFile /dev/null
LogVerbose no
LogClean no
ScanPDF yes
ScanArchive yes
HeuristicAlerts yes
AlertEncrypted yes
AlertExceedsMax yes
MaxThreads 2
MaxQueue 4
ReadTimeout 15
CommandReadTimeout 5
MaxScanTime 15000
StreamMaxLength 10M
MaxFileSize 10M
MaxScanSize 32M
MaxFiles 128
MaxRecursion 8
