/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/scanner/wrangler.jsonc --include-runtime=false --env-interface=ScannerEnv apps/scanner/worker-configuration.d.ts` (hash: 1bc3a6b6a96996954ad02e03094fb37d)
interface __BaseEnv_ScannerEnv {
	WRANGLER_VERSION_METADATA: WorkerVersionMetadata;
	SCANNER_CONTAINER: DurableObjectNamespace<import("./src/index").ClamAvContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ClamAvContainer";
	}
	interface Env extends __BaseEnv_ScannerEnv {}
}
interface ScannerEnv extends __BaseEnv_ScannerEnv {}
