/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=ScannerEnv` (hash: a184556bd7288defb59b6965c5fe2b39)
interface __BaseEnv_ScannerEnv {
	SCANNER_CONTAINER: DurableObjectNamespace<import("./src/index").ClamAvContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ClamAvContainer";
	}
	interface Env extends __BaseEnv_ScannerEnv {}
}
interface ScannerEnv extends __BaseEnv_ScannerEnv {}
